### ISSUE TITLE
from_repo hides errors

### ISSUE THREAD

**Issue by avorima** [flaper87/pyhelm#35]
I have a chartmuseum where the charts are stored under `<url>/charts/`. When I run the following:
```
from_repo(<url>, 'mychart')
```
I get no error, but the result is `None`. This means that consecutive actions on that result will fail.

**Comment by ljakimczuk** [comment]
Hi @avorima !

This is related to the closed PR #30 . When the `fname` is used then the `charts/` directory is missed from the absolute path, that's why the charts is not downloaded. In addition, the `RuntimeError('Chart not found in repo')` is raised based on the presence of the chart in the `index.yaml` which is available directly under the `<url>` thus downloaded and verified correctly. Hmm, I guess some extra check could be introduced in the `_get_from_http` after `requests.get` to check of the value is not `None`, to avoid similar cases.

**Comment by avorima** [comment]
Hi @ljakimczuk 

This issue is actually addressing the omitted Exception in the `from_repo` function from [line 119 onwards](https://github.com/flaper87/pyhelm/blob/master/pyhelm/repo.py#L119). I just used my use-case as an example.

I looked through the other issues and it seems like #6 is referring to the same problem.
