### ISSUE TITLE
how to pass argument value as set to helm chart

### ISSUE THREAD

**Issue by arulmeiyappan** [flaper87/pyhelm#55]
servers:
  - name: foo
    port: 80
  - name: bar
    port: 81

The above cannot be expressed with --set in Helm <=2.4. In Helm 2.5, the accessing the port on foo is --set servers[0].port=80. Not only is it harder for the user to figure out, but it is prone to errors if at some later time the order of the servers is changed.

Similar thing i want to pass --set with value from pyhelm. How to do that ?

**Comment by arulmeiyappan** [comment]
Similarly i want to pass the replica number, how to pass any variable input from pyhelm.

**Comment by yanivoliver** [comment]
Sorry for the late response. You can't set specific attributes like that, but you can pass entire record values in a hierarchical manner. 
For example, instead of passing the value as a dict when calling install/update methods in the format of:
``
{"servers[0].port": 80, "servers[1].port": 81}
``
try passing it as:
``
{"servers": [{"port": 80}, {"port", 81}]}
``

Regarding the replica number, just pass it as part of the values when you call install/update.
