### ISSUE TITLE
How to get rendered charts?

### ISSUE THREAD

**Issue by harsh-98** [flaper87/pyhelm#61]
I tried running `chart.get_helm_chart() ` and `chart.dump() ` but none of them gives rendered charts. They still have gotemplate syntax. How do I get rendered charts?

**Comment by yanivoliver** [comment]
The rendering process in Helm is done in its server side component, Tiller. 
In order to see the rendered chart, you can perform a dry run installation of your chart, which will simulate an installation through Tiller, and return you the results without actually performing it.
See the ``dry_run`` flag in ``install_release`` for reference.

**Comment by harsh-98** [comment]
I tried running with dry_run=True.
` tiller.install_release(chart.get_helm_chart(), dry_run=True, namespace='default')`
But even that is returning not rendered templates.

**Comment by yanivoliver** [comment]
Look at the contents of the ``release.manifest`` attribute - it holds the rendered resources.

**Comment by harsh-98** [comment]
Thanks, it is resolved.
